[workspace]
resolver = "2"

members = [
    "examples",
    "rotary",
    "rotary-core",
    "rotary-device",
    "rotary-generator",
    "rotary-device-bindings",
    "bittle",
    "ste",
]

default-members = [
    "rotary",
    "rotary-core",
    "rotary-device",
    "rotary-generator",
    "rotary-device-bindings",
    "bittle",
    "ste",
]

[patch.crates-io]
rotary = {path = "rotary"}
rotary-core = {path = "rotary-core"}
