[package]
name = "audio-device"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

[features]
default = ["wasapi"]
xaudio2 = ["bindings/xaudio2"]
wasapi = ["bindings/wasapi"]

[dependencies]
thiserror = "1.0.24"
rand = "0.8.3"
ste = {path = "../ste"}

[dev-dependencies]
audio-core = {path = "../audio-core"}
audio-generator = {path = "../audio-generator"}
anyhow = "1.0"
tokio = {version = "1.4.0", features = ["full"]}

[target.'cfg(windows)'.dependencies]
bindings = {package = "audio-device-bindings", path = "../audio-device-bindings"}
windows = {git = "https://github.com/microsoft/windows-rs", default-features = false}
