[package]
name = "audio-device"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

[features]
default = ["wasapi"]
wasapi = ["windows", "windows-sys/wasapi"]
alsa = ["libc", "alsa-sys"]

[dependencies]
thiserror = "1.0.24"
rand = "0.8.3"
ste = {path = "../ste"}

[dev-dependencies]
audio-core = {path = "../audio-core"}
audio-generator = {path = "../audio-generator"}
anyhow = "1.0"
tokio = {version = "1.4.0", features = ["full"]}

[target.'cfg(windows)'.dependencies]
windows-sys = {package = "audio-device-windows-sys", path = "../audio-device-windows-sys"}
windows = {git = "https://github.com/microsoft/windows-rs", default-features = false, optional = true}

[target.'cfg(unix)'.dependencies]
alsa-sys = {package = "audio-device-alsa-sys", path = "../audio-device-alsa-sys", optional = true}
libc = {version = "0.2.93", optional = true}
nix = "0.20.0"

[[example]]
name = "alsa-list"
required-features = ["alsa"]

[[example]]
name = "alsa-open"
required-features = ["alsa"]
