[package]
name = "rotary-device-bindings"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

[dependencies]
windows_macros = {git = "https://github.com/microsoft/windows-rs"}
windows_gen = {git = "https://github.com/microsoft/windows-rs"}
