[package]
name = "audio-generator"
version = "0.2.0-alpha.4"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
keywords = ["buffer", "audio", "dsp"]
categories = ["multimedia::audio"]
repository = "https://github.com/udoprog/audio"
homepage = "https://github.com/udoprog/audio"
documentation = "https://docs.rs/audio-generator"
description = "Audio generator APIs"
readme = "README.md"

[dependencies]
audio-core = {version = "0.2.0-alpha.4", path = "../audio-core"}
